name: Azure API CI/CD - Backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_backend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      # Set up .NET 8
      - name: Set up .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      
      # Install dependencies and build the solution
      - name: Install dependencies
        run: dotnet restore ./RealTimeChatApp.sln

      - name: Build the solution
        run: dotnet build --configuration Release ./RealTimeChatApp.sln

      # Publish the API project
      - name: Publish API
        run: dotnet publish ./Api/Api.csproj --configuration Release --output ./api_publish

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-azure-web-app-name'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./api_publish
